apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-cronjob
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: 'worker'
            image: poltweetexregistry.azurecr.io/myworker
            env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresql-password
                  name: postgres-password