apiVersion: batch/v1
kind: Job
metadata:
  name: 'update-job'
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: 'worker'
        image: poltweetexregistry.azurecr.io/myworker
        env:
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: postgres-password
        - name: POSTGRESQL_URL
          value: postgres-postgresql
        - name: POSTGRESQL_NAME
          value: exampledb
        - name: API_Key
          valueFrom:
            secretKeyRef:
              key: twitter-secret
              name: api-key
        - name: API_Secret_Key
          valueFrom:
            secretKeyRef:
              key: twitter-secret
              name: api-secret-key
        - name: Access_Token
          valueFrom:
            secretKeyRef:
              key: twitter-secret
              name: access-token
        - name: Access_Token_Secret
          valueFrom:
            secretKeyRef:
              key: twitter-secret
              name: access-token-secret