apiVersion: batch/v1
kind: Job
metadata:
  name: 'update-job'
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: 'worker'
        image: poltweetexregistry.azurecr.io/myworker
        env:
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: postgres-password
        - name: POSTGRESQL_URL
          value: postgres-postgresql
        - name: POSTGRESQL_NAME
          value: exampledb
        - name: API_Key
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: api-key
        - name: API_Secret_Key
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: api-secret-key
        - name: Access_Token
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: access-token
        - name: Access_Token_Secret
          valueFrom:
            secretKeyRef:
              name: twitter-secret
              key: access-token-secret
        - name: SETUP_DB
          value: "true"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: app-config